---
abstract: 'Dcrt IVR'
author:
  - 'Georgi Manev <gmanev@newtech-bt.bg>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120630'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: dcrt-ivr
provides:
  Dcrt::AGIService:
    file: lib/AGIService.pm
    version: 0
  Dcrt::AGIService::LogHandle:
    file: lib/LogHandle.pm
    version: 0
  Dcrt::IVR::RecordCode:
    file: lib/IVR/RecordCode.pm
    version: 0
  Dcrt::IVR::RegisterCode:
    file: lib/IVR/RegisterCode.pm
    version: 0
requires:
  Asterisk::FastAGI: 0.02
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: v0.0.1
